apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod1
  name: pod1
spec:
  containers:
  - command:
    - sleep
    - "1000"
    image: busybox
    name: pod1
    resources: {}
  dnsPolicy: Default
  restartPolicy: Always
status: {}
